// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuyensinhVido.Data;

#nullable disable

namespace TuyensinhVido.Migrations
{
    [DbContext(typeof(TuyensinhDbContext))]
    [Migration("20220831043211_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TuyensinhVido.Models.Nganh", b =>
                {
                    b.Property<int?>("id")
                        .HasColumnType("int");

                    b.Property<string>("KhoiThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KyHieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("heDaoTaoId")
                        .HasColumnType("int");

                    b.Property<int?>("khoaId")
                        .HasColumnType("int");

                    b.Property<string>("ma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenTA")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tbl_Nganh");
                });

            modelBuilder.Entity("TuyensinhVido.Models.Tuyensinh", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("CMND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hocba")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hoten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NganhId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NganhId");

                    b.ToTable("tbl_Tuyensinh");
                });

            modelBuilder.Entity("TuyensinhVido.Models.Tuyensinh", b =>
                {
                    b.HasOne("TuyensinhVido.Models.Nganh", "Nganh")
                        .WithMany()
                        .HasForeignKey("NganhId");

                    b.Navigation("Nganh");
                });
#pragma warning restore 612, 618
        }
    }
}
