// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuyensinhVido.Data;

#nullable disable

namespace TuyensinhVido.Migrations
{
    [DbContext(typeof(TuyensinhDbContext))]
    partial class TuyensinhDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TuyensinhVido.Models.Hinhanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImageTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThiSinhId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThiSinhId");

                    b.ToTable("tbl_Hinhanh");
                });

            
            modelBuilder.Entity("TuyensinhVido.Models.Tuyensinh", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("CMND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hocba")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hoten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NganhId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NganhId");

                    b.ToTable("tbl_Tuyensinh");
                });

            modelBuilder.Entity("TuyensinhVido.Models.Hinhanh", b =>
                {
                    b.HasOne("TuyensinhVido.Models.Tuyensinh", "ThiSinh")
                        .WithMany("Hinhanh")
                        .HasForeignKey("ThiSinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThiSinh");
                });

            modelBuilder.Entity("TuyensinhVido.Models.Tuyensinh", b =>
                {
                    b.HasOne("TuyensinhVido.Models.Nganh", "Nganh")
                        .WithMany()
                        .HasForeignKey("NganhId");

                    b.Navigation("Nganh");
                });

            modelBuilder.Entity("TuyensinhVido.Models.Tuyensinh", b =>
                {
                    b.Navigation("Hinhanh");
                });
#pragma warning restore 612, 618
        }
    }
}
